Repository meateam/seal, pull requests merged in 2018-07, with the labels that each got.

#22 User
  package-lock.json
  package.json
  src/config.ts
  src/errors/application.ts
  src/errors/user.ts
  src/helpers/controller.helper.ts
  src/helpers/enums.ts
  src/helpers/functions.ts
  src/server.ts
  src/user/user.controller.ts
  src/user/user.model.ts
  src/user/user.router-spec.ts
  src/user/user.router.ts
  src/user/user.service.ts
  src/user/user.spec.ts
  src/user/user.validator.ts
  tslint.json
Labels: Pull Request, User

#26 Share
  mocha.opts
  package-lock.json
  package.json
  src/helpers/controller.helper.ts
  src/helpers/repository.ts
  src/helpers/spec.helper.ts
  src/helpers/warpAsync.ts
  src/server.ts
  src/share/share.controller.ts
  src/share/share.interface.ts
  src/share/share.model.ts
  src/share/share.repository.ts
  src/share/share.responder.ts
  src/share/share.router.ts
  src/share/share.spec.ts
  src/user/user.router.spec.ts
  src/user/user.spec.ts
Labels: Feature

#30 refactor - changes the router file location.
  src/router.ts
  src/server.ts
Labels: Code Architecture

#50 Error handler
  src/errors/application.ts
  src/router.ts
Labels: Pull Request
